# General Parameters
project_name: "ImageClassificationDVC"
data_path: "data"
processed_data_path: "data/processed"
model_path: "models/model.pth"
reports_path: "reports/metrics.json"

# Data Collection Parameters
dataset_name: "CIFAR10"

# Data Processing Parameters
image_size: 32
batch_size: 64
test_split_ratio: 0.2
validation_split_ratio: 0.15

# Model Training Parameters
epochs: 15
learning_rate: 0.001
optimizer: "Adam" # Options: Adam, SGD
momentum: 0.9 # Only for SGD
dropout_rate: 0.25
num_classes: 10

# Model Architecture
conv1_out_channels: 32
conv2_out_channels: 64
fc1_out_features: 128
